package com.jarvis.assistant.armor

/**
 * Iron Man armor catalog — Mark I → Mark XLII (+ extras from the suit chart).
 * Colors approximate each suit for HUD / liquid-glass tint.
 */
data class ArmorMark(
    val number: Int,
    val roman: String,
    val codename: String,
    val era: String,
    val primaryHex: String,
    val secondaryHex: String,
    val summary: String,
    val structure: List<String>
)

object ArmorCatalog {

    val all: List<ArmorMark> = listOf(
        ArmorMark(1, "I", "Mark I", "Iron Man (2008)", "#5A5A5A", "#8B7355",
            "Cave-built prototype in Afghanistan. Crude iron plates, flamethrowers, limited flight.",
            listOf("Hand-forged iron plating", "Crude boot jets", "Flamethrower gauntlets", "No sealed life support", "External power cells")),
        ArmorMark(2, "II", "Mark II", "Iron Man (2008)", "#C0C0C0", "#A8A8A8",
            "First polished silver suit. Solved icing at altitude; basis for later designs.",
            listOf("Machined steel alloy shell", "Improved thrusters", "Repulsor prototypes", "Altitude icing issue", "HUD v1")),
        ArmorMark(3, "III", "Mark III", "Iron Man (2008)", "#C41E3A", "#F5C518",
            "Classic red-and-gold. Public debut vs. Iron Monger.",
            listOf("Gold-titanium alloy", "Full flight system", "Repulsors + unibeam", "Missile micro-racks", "Sealed life support")),
        ArmorMark(4, "IV", "Mark IV", "Iron Man 2", "#C41E3A", "#F5C518",
            "Refined Mark III for daily wear and party entrance.",
            listOf("Lighter alloy panels", "Faster helmet deploy", "Improved power efficiency", "Same red-gold scheme", "Stable thrusters")),
        ArmorMark(5, "V", "Mark V", "Iron Man 2", "#C0C0C0", "#C41E3A",
            "Portable suitcase armor — rapid deploy in Monaco.",
            listOf("Suitcase form factor", "Rapid assemble", "Lightweight plates", "Short combat endurance", "Red accents")),
        ArmorMark(6, "VI", "Mark VI", "Iron Man 2 / Avengers", "#C41E3A", "#F5C518",
            "Triangular RT chest. New element core; Battle of New York.",
            listOf("Triangular arc reactor", "New element power", "Enhanced output", "Repulsor upgrade", "Avengers-ready")),
        ArmorMark(7, "VII", "Mark VII", "Avengers (2012)", "#C41E3A", "#F5C518",
            "Pod-deployed. Auto-assemble around Tony mid-fall.",
            listOf("Autonomous pod deploy", "Self-assemble rings", "High maneuver thrusters", "Extra missile load", "Battle of NY config")),
        ArmorMark(8, "VIII", "Mark VIII", "Post-Avengers", "#C41E3A", "#F5C518",
            "Incremental refinement after New York.",
            listOf("Reinforced joints", "Better heat management", "Standard red-gold", "Improved HUD", "Stable flight")),
        ArmorMark(9, "IX", "Mark IX", "Iron Man 3 era", "#C41E3A", "#F5C518",
            "Early House Party Protocol generation.",
            listOf("Modular hardpoints", "Prehensile test mounts", "Red-gold finish", "Telemetry uplink", "Workshop standby")),
        ArmorMark(10, "X", "Mark X", "Iron Man 3 era", "#C41E3A", "#F5C518",
            "Continued modular experiments.",
            listOf("Lightweight frame", "Fast swap modules", "Standard scheme", "Combat ready", "Remote recall")),
        ArmorMark(11, "XI", "Mark XI", "Iron Man 3 era", "#C41E3A", "#F5C518",
            "House Party line — general combat.",
            listOf("Balanced offense/defense", "Repulsor focus", "Red-gold", "Autonomous capable", "Workshop rack")),
        ArmorMark(12, "XII", "Mark XII", "Iron Man 3 era", "#4A4A4A", "#C0C0C0",
            "Stealth-leaning dark finish variant.",
            listOf("Dark alloy coat", "Reduced radar signature", "Quiet thrusters", "Night ops HUD", "Light armament")),
        ArmorMark(13, "XIII", "Mark XIII", "Iron Man 3 era", "#3D3D3D", "#6A6A6A",
            "Dark tactical suit.",
            listOf("Matte dark plates", "Enhanced sensors", "Silent mode", "Close combat bias", "Black-ops paint")),
        ArmorMark(14, "XIV", "Mark XIV", "Iron Man 3 era", "#2F2F2F", "#5A5A5A",
            "Further stealth iteration.",
            listOf("Absorptive coating", "Low IR signature", "Compact thrusters", "Minimal gold", "Infiltration role")),
        ArmorMark(15, "XV", "Sneaky", "Iron Man 3", "#1A1A1A", "#3A3A3A",
            "Stealth specialist — near-invisible profile.",
            listOf("Active camouflage trials", "Silent flight", "Black finish", "Recon sensors", "Non-lethal options")),
        ArmorMark(16, "XVI", "Nightclub", "Iron Man 3", "#1C1C1C", "#C41E3A",
            "Black with red highlights — night operations.",
            listOf("Black primary armor", "Red RT glow", "Urban night kit", "Fast deploy", "House Party node")),
        ArmorMark(17, "XVII", "Heartbreaker", "Iron Man 3", "#C41E3A", "#F5C518",
            "Heavy unibeam specialist — chest energy focus.",
            listOf("Oversized chest RT", "High-output unibeam", "Reinforced torso", "Energy weapon bias", "Red-gold")),
        ArmorMark(18, "XVIII", "Casanova", "Iron Man 3", "#2A2A2A", "#4A4A4A",
            "Dark suit, social/infiltration naming.",
            listOf("Dark chrome", "Subtle profile", "Standard armament", "Telemetry suite", "Autonomous OK")),
        ArmorMark(19, "XIX", "Tiger", "Iron Man 3", "#C41E3A", "#F5C518",
            "Agile striker — speed over armor bulk.",
            listOf("Lightweight limbs", "High agility thrusters", "Claw-style gauntlets", "Red-gold", "Fast intercept")),
        ArmorMark(20, "XX", "Python", "Iron Man 3", "#C41E3A", "#F5C518",
            "Flexible joint design — contortion / tight spaces.",
            listOf("Hyper-articulate joints", "Snake-like mobility", "Standard weapons", "Red-gold", "Close quarters")),
        ArmorMark(21, "XXI", "Midas", "Iron Man 3", "#D4AF37", "#F5C518",
            "Full gold ceremonial / high-visibility suit.",
            listOf("Gold primary finish", "Showpiece armor", "Standard internals", "High polish", "Public appearance")),
        ArmorMark(22, "XXII", "Hot Rod", "Iron Man 3", "#C41E3A", "#1A1A1A",
            "Black and red — hot-rod aesthetic, aggressive.",
            listOf("Black-red scheme", "Boosted thrusters", "Sport handling", "Flashy RT", "Speed bias")),
        ArmorMark(23, "XXIII", "Shades", "Iron Man 3", "#C0C0C0", "#8A8A8A",
            "Silver reflective finish.",
            listOf("Mirror chrome", "Heat reflective", "Standard loadout", "Show + combat", "Bright signature")),
        ArmorMark(24, "XXIV", "Tank", "Iron Man 3", "#5C4033", "#8B6914",
            "Heavy armor — maximum protection.",
            listOf("Thick plating", "Slow heavy thrusters", "High mass", "Siege role", "Bronze-brown tone")),
        ArmorMark(25, "XXV", "Striker", "Iron Man 3", "#5A5A5A", "#3A3A3A",
            "Ground assault emphasis.",
            listOf("Reinforced legs", "Heavy gauntlets", "Grey tactical", "Shock absorption", "Breach role")),
        ArmorMark(26, "XXVI", "Gamma", "Iron Man 3", "#2E8B57", "#1B4D3E",
            "Green radiation-oriented experiment.",
            listOf("Radiation shielding", "Green alloy coat", "Sensor suite", "Lab origin", "Specialist")),
        ArmorMark(27, "XXVII", "Disco", "Iron Man 3", "#1E3A8A", "#F5C518",
            "Blue and gold high-visibility suit.",
            listOf("Blue primary plates", "Gold trim", "Bright RT", "Show + combat", "Unique paint")),
        ArmorMark(28, "XXVIII", "Jack", "Iron Man 3", "#C45C26", "#8B4513",
            "Orange-brown workhorse.",
            listOf("Orange-brown finish", "Utility hardpoints", "Durable joints", "Field repair bias", "Generalist")),
        ArmorMark(29, "XXIX", "Fiddler", "Iron Man 3", "#2F2F2F", "#5A5A5A",
            "Precision / fine-manipulation specialist.",
            listOf("High-dexterity hands", "Fine motor servos", "Dark finish", "Tech interaction", "Delicate tasks")),
        ArmorMark(30, "XXX", "Blue Steel", "Iron Man 3", "#1E90FF", "#0A4A7A",
            "Blue steel finish — cool visual + heat management.",
            listOf("Blue steel alloy look", "Heat dissipation", "Standard weapons", "Distinct HUD tint", "Specialist paint")),
        ArmorMark(31, "XXXI", "Piston", "Iron Man 3", "#2F4F4F", "#1A3A3A",
            "Mechanical strength focus — piston-assisted limbs.",
            listOf("Hydraulic assist", "High lift strength", "Dark teal-grey", "Heavy labor", "Reinforced arms")),
        ArmorMark(32, "XXXII", "Romeo", "Iron Man 3", "#1A1A2E", "#0F0F1A",
            "Dark navy / black romantic codename suit.",
            listOf("Near-black navy", "Subtle gold", "Stealth lean", "Standard RT", "Autonomous")),
        ArmorMark(33, "XXXIII", "Silver Centurion", "Iron Man 3", "#C41E3A", "#C0C0C0",
            "Red and silver. Enhanced power, classic comic nod.",
            listOf("Red + silver plates", "Upgraded RT output", "Strong thrusters", "Centurion heritage", "Frontline combat")),
        ArmorMark(34, "XXXIV", "Southpaw", "Iron Man 3", "#2A2A2A", "#4A4A4A",
            "Asymmetric / left-dominant combat tuning.",
            listOf("Asymmetric gauntlets", "Left-hand bias", "Dark finish", "Close combat", "Specialist")),
        ArmorMark(35, "XXXV", "Red Snapper", "Iron Man 3", "#C41E3A", "#8B0000",
            "Heavy claws / gripping appendages.",
            listOf("Snapper claw systems", "Deep red armor", "Grab & crush", "Industrial salvage", "Non-standard hands")),
        ArmorMark(36, "XXXVI", "Peacemaker", "Iron Man 3", "#B8860B", "#DAA520",
            "Gold-orange negotiation / non-lethal lean.",
            listOf("Gold-orange scheme", "Non-lethal options", "Presence suit", "Diplomacy optics", "Standard flight")),
        ArmorMark(37, "XXXVII", "Hammerhead", "Iron Man 3", "#2E5A3C", "#1A3A28",
            "Green heavy ramming / reinforced skull design.",
            listOf("Reinforced helmet", "Ramming mass", "Green armor", "Breach specialist", "Heavy skull plate")),
        ArmorMark(38, "XXXVIII", "Igor", "Iron Man 3", "#1E3A5F", "#0D2137",
            "Heavy construction / lifting suit — bulky.",
            listOf("Massive frame", "Construction servos", "Blue-heavy paint", "Max lift", "Slow flight")),
        ArmorMark(39, "XXXIX", "Starboost", "Iron Man 3", "#E8E8E8", "#C0C0C0",
            "Space / high-altitude booster configuration.",
            listOf("White thermal coat", "Extended thrusters", "Vacuum seals", "Orbital capable", "Starboost packs")),
        ArmorMark(40, "XL", "Shotgun", "Iron Man 3", "#2C2C2C", "#1A1A1A",
            "Rapid multi-shot projectile emphasis.",
            listOf("Multi-barrel micro-munitions", "Dark tactical", "Burst fire", "Close-mid range", "Aggressive profile")),
        ArmorMark(41, "XLI", "Bones", "Iron Man 3", "#3D3D3D", "#C9A227",
            "Skeletal exposed-frame experimental suit.",
            listOf("Exposed exo-frame", "Minimal plating", "Gold joint accents", "Ultra-light", "Experimental")),
        ArmorMark(42, "XLII", "Mark XLII", "Iron Man 3", "#C41E3A", "#F5C518",
            "Prehensile autonomous armor. Assembles piece-by-piece onto Tony. Final House Party node.",
            listOf("Prehensile autonomous plates", "Piece-by-piece assemble", "Remote call", "Red-gold classic", "Damaged in final battle", "Emotional core suit"))
    )),

        ArmorMark(85, "LXXXV", "Mark 85 (Nanotech)", "Avengers: Endgame", "#C41E3A", "#F5C518",
            "Final nanotech suit built for the battle against Thanos. Assembles from a wrist-mounted nanoparticle core, forming wings, energy whips, a sword, and a full arsenal on demand.",
            listOf("Nanotech self-assembly", "Wrist-core storage", "Wing energy blades", "Repulsor + unibeam", "Sword mode", "Full HUD suite", "Adaptive weapon forming"))
    )

    fun byNumber(n: Int): ArmorMark? = all.find { it.number == n }

    fun search(query: String): ArmorMark? {
        val q = query.trim().lowercase()
        // "mark 33", "mark xxxiii", "silver centurion", "42"
        val num = Regex("""(?:mark\s*)?(\d{1,2})""").find(q)?.groupValues?.get(1)?.toIntOrNull()
        if (num != null) return byNumber(num)
        return all.find {
            it.codename.lowercase().contains(q) ||
            it.roman.lowercase() == q ||
            it.codename.lowercase().replace("mark ", "") == q
        }
    }
}
